#!/usr/bin/env bash
# Rhea — build a Flipper Zero BadUSB script that types the passphrase.
#
# WHY THIS AND NOT A KEYFILE ON THE DRIVE: a key stored beside the repo it
# opens means whoever picks up the drive has everything. Putting it on the
# Flipper instead splits the secret from the data — the drive alone is an
# encrypted brick, and you need both objects to restore. That is the difference
# between encryption that means something and encryption that is decoration.
#
#   ./rhea-make-badusb.sh                 write rhea-unlock.txt to ~/Desktop
#   ./rhea-make-badusb.sh /path/out.txt   write it somewhere specific
#
# Then copy it to the Flipper: qFlipper, or the SD card directly, into
#   /ext/badusb/rhea-unlock.txt
# At the restore prompt: Flipper → Bad USB → rhea-unlock → Run.
#
# THE FLIPPER IS NOT THE DURABLE COPY. It gets carried, dropped, borrowed and
# occasionally confiscated. If it is the only place the key exists you have
# rebuilt the original bug in a smaller object. Keep the printed copy.
set -euo pipefail

PASSFILE="${PASSFILE:-/home/astroson/.config/rhea/passphrase}"
OUT="${1:-$HOME/Desktop/rhea-unlock.txt}"

[ -r "$PASSFILE" ] || { echo "FATAL: no passphrase at $PASSFILE" >&2; exit 1; }
PASS="$(tr -d '\r\n' < "$PASSFILE")"
[ -n "$PASS" ] || { echo "FATAL: passphrase file is empty" >&2; exit 1; }

# DuckyScript STRING sends one line of printable ASCII. Anything outside that
# will not type correctly, and a passphrase that types WRONG is worse than one
# that does not type at all — you would be told the repo cannot be opened and
# have no idea why.
if printf '%s' "$PASS" | LC_ALL=C grep -qP '[^\x20-\x7e]'; then
  echo "FATAL: the passphrase contains non-printable or non-ASCII characters." >&2
  echo "BadUSB cannot type those reliably. Use the printed copy, or rotate the" >&2
  echo "passphrase to printable ASCII (which means re-keying the repo)." >&2
  exit 1
fi

umask 077
cat > "$OUT" <<EOF
REM Rhea restore — types the restic passphrase at the rhea-restore.sh prompt.
REM Generated by rhea-make-badusb.sh. This file IS the secret: treat the
REM Flipper like a key, because that is now what it is.
REM
REM Layout: assumes a US keyboard on the target. On another layout the symbols
REM will mistype and the repo will simply refuse to open.
DELAY 800
STRING $PASS
ENTER
EOF
chmod 600 "$OUT"

echo "wrote $OUT"
echo
echo "  1. copy it to the Flipper at /ext/badusb/rhea-unlock.txt"
echo "  2. make sure the drive does NOT also carry the key:"
echo "         sudo ./rhea-seed-key.sh --check"
echo "     (if it does, the Flipper adds nothing — remove the drive keyfile)"
echo "  3. fire drill it once, on purpose, before you need it:"
echo "         sudo ./rhea-restore.sh --scratch /tmp/rhea-drill"
echo
echo "  And print the passphrase. The Flipper is the convenient copy;"
echo "  paper is the one that survives losing the Flipper."
